- name: Copy war file to apps dir
  copy:
      src="{{ base_dirs.software }}/{{ item.war }}"
      dest="{{ base_dirs.tomcat }}/{{ instance.name }}/apps"
  with_items: "{{ instance.apps }}"

- name: Create Catalina localhost directory
  file: state=directory path="{{ base_dirs.tomcat }}/{{ instance.name }}/conf/Catalina/localhost"

- name: Copy context path xml file to Catalina localhost directory
  template:
      src=context.xml
      dest="{{ base_dirs.tomcat }}/{{ instance.name }}/conf/Catalina/localhost/{{ item.context_root }}.xml"
  with_items: "{{ instance.apps }}"
  tags: [ mpo_debug ]
