---
-  hosts:            tc-servers
   remote_user:      remote_user
   become:           true
   become_user:      "{{ users.tomcat_home.name }}"
   gather_facts:     false

   pre_tasks:
      - debug: var=users.tomcat_home.name
      - debug: var=files
      - debug: var=base_dirs
      - debug: var=dirs.tomcat_tars
      - debug: var=dirs
      - debug: var=versions
      - include: roles/tomcat-common/tasks/copy_archive.yml


   roles:
      - { role: tomcat-home }


