---
-  hosts:            tc-servers
   remote_user:      remote_user
   become:           true
   become_user:      "{{ users.tomcat_home.name }}"
   gather_facts:     false

   pre_tasks:
      - include: roles/tomcat-common/unarchive.yml
      - debug: var=users.tomcat_home.name

   roles:
      - { role: tomcat-home }


