- name: Create a dir for install tars
  file: path={{ dirs.tomcat_tars }} state=directory

- name: Copy install tar to remote server
  copy:
      src={{ base_dirs.software }}/{{ files.tomcat_install_tar }}
      dest={{ dirs.tomcat_tars }}

